Dev
	- Scenario: Create database schema
		- ThirdAPI.RequestDatabase()
		- DatabaseSchemaManagementAPI.CreateCollection()
		- DatabaseSchemaManagementAPI.ApplyToSandboxEnvironment()
		- DatabaseSchemaManagementAPI.ApplyToProductionEnvironment()
	// แตก scenario ให้ละเอียด
	- Scenario: Change database schema
		- DatabaseSchemaManagementAPI.CreateCollection()
		- DatabaseSchemaManagementAPI.ConfigCollection()
		- DatabaseSchemaManagementAPI.DeleteCollection()
		- DatabaseSchemaManagementAPI.SetupCollectionMappings()
		- DatabaseSchemaManagementAPI.ApplyToSandboxEnvironment()
		- DatabaseSchemaManagementAPI.ApplyToProductionEnvironment()
	// external must reg api ? / internal only create db ?
	- Scenario: Prepare product api
		- ThirdAPI.RegisterProductApi()

Merchant
	- Scenario: Merchant subscribe service
		* ManaMobileAPI.SubscribeService()
			- ManaSystem => Create Database by schema
			- ManaSystem => Hook to Dev
		- Dev => Init database data
			- DatabaseManagementAPI.CreateDocument()

	- Scenario: Create product data
		[Product]
		- DatabaseManagementAPI.CreateDocument()
		[Options]
		- DatabaseManagementAPI.CreateDocument()

	- Scenario: Register product to mana
		* ThirdAPI.RegisterMContent()
		* ThirdAPI.RegisterOptionMContent()
		* ThirdAPI.MappingOptionMContent() ???
		- ThirdAPI.RegisterProduct()
		{ 
			name: shoes,
			mcontentUrl: ManaMobileAPI.GetProductMContent(),
			dataHookUrl: ManaMobileAPI.GetProduct()
			// กำหนดทีเดียวใช้ได้หลาย product
			options:[
				{ optionMContentId: "mct123", dataHookUrl: "" }
				{ optionMContentId: "mct456", dataHookUrl: "" }
			]
		}
		* Register CollectibleOptions
		***** how to use mcontent option? *****

User
	- Scenario: User scan QR
		* Visit()
		* FormController.GetMContent()
			- ManaMobileAPI.GetProductMContent()
		* FormController.GetData()
			- ManaMobileAPI.GetProduct()
		* ManaMobileAPI.GetOptionMContent()
			- ?????

	***** Cart scenario => ลงรายละเอียดไปจนถึงตอนดึงข้อมูล
	- Scenario: User add product to cart
		* FormController.Submit()
		* ProductHook()
		* CartHook()

	- Scenario: User checkout
		* TakeAction()
		* OrderHook()

	- Scenario: User pay
		* TakeAction()
		* PaymentHook()

*** Grant db for another service
*** Who is db owner? merchant or service or both
