Dev
	- Scenario: Request Database
		- ThirdAPI.RequestDatabase()
		{
			databasename: "promome"
			productCollectionname: "Product",
		}

	- Scenario: Create database schema => example [product option], [shop table], [order], [OpenShop]
		- DatabaseSchemaManagementAPI.CreateCollection("ProductOption")
		- DatabaseSchemaManagementAPI.CreateCollection("ShopTable")
		- DatabaseSchemaManagementAPI.CreateCollection("order")
		- DatabaseSchemaManagementAPI.CreateCollection("OpenShop")

		***schemaname for reference to collections

	- scenario: Deploy schema to sandbox for test with dev merchant
		- DatabaseSchemaManagementAPI.DeployToSandboxEnvironment(schemaname)

	- scenario: Create dev merchant on sandbox and test
		*** ควรแยก environment หรือไม่
		* ThirdAPISandbox.RegisterMContent()
		* ThirdAPISandbox.RegisterOptionMContent()
		* ThirdAPISandbox.MappingOptionMContent() ???
		* ThirdAPISandbox.CreateDevMerchant()
		* ManaMobileAPISandbox.SubscribeService()
		- DatabaseManagementAPISandbox.CreateDocument() // create product data
		- ThirdAPISandbox.RegisterProduct()
		* ... cart scenario on sandbox ...

	- Scenario: Change database schema
		- DatabaseSchemaManagementAPI.CreateCollection("bill")
		- DatabaseSchemaManagementAPI.DropCollection("OpenShop")
		- DatabaseSchemaManagementAPI.DeployToSandboxEnvironment()
		* ... cart scenario on sandbox again ...

	- scenario: Deploy schema to production
		- DatabaseSchemaManagementAPI.DeployToProductionEnvironment()

		
	- Scenario: prepare product mcontent
		* ThirdAPI.RegisterMContent()
		* ThirdAPI.RegisterOptionMContent()
		* ThirdAPI.MappingOptionMContent() ???

	- Scenario: External product prepare product api
		- ThirdAPI.RegisterProductApi()

Merchant
	- Scenario: Merchant subscribe service
		* ManaMobileAPI.SubscribeService()
			- ManaSystem => Create Database by schema
			- ManaSystem => Hook to Dev
		- Service => Init database data
			- DatabaseManagementAPI.CreateDocument()
		- Service => ThirdAPI.ApproveSubscription() / ThirdAPI.DeclineSubscription()

	- Scenario: Create product data
		[Product]
		- DatabaseManagementAPI.CreateDocument()
		[Options]
		- DatabaseManagementAPI.CreateDocument()

	- Scenario: Register product to mana
		- ThirdAPI.RegisterProduct()
		{ // แบบ 4
			id: pro123
			name: shoes,
			mcontentUrl: ManaMobileAPI.GetProductMContent(),
			dataHookUrl: ManaMobileAPI.GetProduct(),
			options:[
				{"color":["red","green","blue"]}
				{"size":["s","m","l"]}
			],
			optionPrices:[
				{id:"pro123", color:"red", size:"s", price:5},
				{id:"pro123", color:"green", size:"s", price:7},
				{id:"pro123", color:"blue", size:"s", price:10},
				{id:"pro124", color:"red", size:"m", price:5},
				{id:"pro125", color:"green", size:"m", price:20},
				{id:"pro126", color:"blue", size:"m", price:2},
			],
		}
		* ไม่ต้องเอาเรื่อง stock มาเกี่ยวในขั้นตอนนี้

		* Register CollectibleOptions
		***** how to use mcontent option? *****

User
	- Scenario: User scan product QR
		* Visit()
		* FormController.GetMContent()
			- ManaMobileAPI.GetProductMContent()
		* FormController.GetData()
			- ManaMobileAPI.GetProduct()
		* ManaMobileAPI.GetOptionMContent()
			- ?????

	***** Cart scenario => ลงรายละเอียดไปจนถึงตอนดึงข้อมูล
	* FormController.Submit()
	
	- Scenario: User add coupon to cart
		* CartHook()
			ThirdAPI.GetCoupon()  			
		
	- Scenario: User add product to cart
		* ProductHook()
			DatabaseManagementAPI.GetDocument("stock", productid)  			
		* CartHook()
			DatabaseManagementAPI.GetDocument("stock", productids) : Check stock	

	- Scenario: User checkout
		* TakeAction()
		* OrderHook()
			DatabaseManagementAPI.EditDocument("stock", productid) : Check stock

	- Scenario: User pay
		* TakeAction()
		* PaymentHook()



ตั้งแต่ dev เริ่ม register 
    - ต้องมี hook อะไรบ้าง ?
create DB ใส่ schema ด้วยเลย ?

ร้าน subscribe รอ processing
หลังร้าน subscribe ต้องส่ง url หรือบางอย่างให้ร้านจัดการ เช่น mcontent urlmanage


